source "https://rubygems.org"
git_source(:github) {|repo| "https://github.com/#{repo}.git" }

ruby "3.1.2"

# Rails本体（標準gem）
gem "rails", "~> 7.0.4"

# MySQLに接続する
gem "mysql2", "~> 0.5"

# Pumaサーバーを使えるようにする(標準gem) [https://github.com/puma/puma]
gem "puma", "~> 5.0"

# CORS設定を管理する
gem "rack-cors"

# タイムゾーン情報を提供する（標準gem）
gem "tzinfo-data", platforms: %i[mingw mswin x64_mingw jruby]

# Railsの起動時間を短縮する（標準gem）
gem "bootsnap", require: false

# 環境ごとの設定管理を行う
gem "config"

group :development, :test do
  # pryコンソールを使えるようにする
  gem "pry-byebug"
  gem "pry-doc"
  gem "pry-rails"
  # テストフレームワーク rspec を導入
  gem "rspec-rails"

  # rubocopを使えるようにする
  gem "rubocop-faker"
  gem "rubocop-rails"
  gem "rubocop-rspec"
end
